[package]
name = "lylib"
version = "0.25.7"
edition = "2021"

[dependencies]
anyhow = "1.0"
derivative = "2.2"
rustc-hash = "2.1"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "interpret"
harness = false
