[package]
name = "lylib"
version = "0.14.17"
edition = "2021"

[dependencies]
anyhow = "1.0"
rustc-hash = "1.1"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "interpret"
harness = false
