[package]
name = "lylib"
version = "0.20.17"
edition = "2021"

[dependencies]
anyhow = "1.0"
rustc-hash = "2.1"

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "interpret"
harness = false
